# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 225ce3c5f3f009521eb2e66b0600874c6483ca56faf140512fb0ee7e96b1a4dc34434d258d0e95f784acb19a87844e03b079955e3e5d02678e590e6472897b28

test:
  secret_key_base: d720709d9b708a9daa524a74733bb653aa75c6826c05ead308aa25c136cf314e42637bfb30ae0bd2a0fdd83221e15ea976c2e994902eba1994d2d000ad06fe44

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
